### ISSUE TITLE
Add script name completion for `yarn run`

### ISSUE THREAD

**Issue by gluons** [gluons/posh-yarn-completion#3]
Read scripts from `package.json` via [`ConvertFrom-Json`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-json) and add it to completion.

**Comment by guillaume86** [comment]
Hi, nice work!

Could you also include these completions to the default ´yarn [tab]´ completion list to mirror yarn behavior? (`yarn start` is a shortcut for `yarn run start` for example).
